if(EXISTS "/home/runner/work/sageFlow/sageFlow/_codeql_build_dir/test/test_window_pipeline[1]_tests.cmake")
  include("/home/runner/work/sageFlow/sageFlow/_codeql_build_dir/test/test_window_pipeline[1]_tests.cmake")
else()
  add_test(test_window_pipeline_NOT_BUILT test_window_pipeline_NOT_BUILT)
endif()
