if(EXISTS "/home/runner/work/sageFlow/sageFlow/_codeql_build_dir/test/test_pipeline_basic[1]_tests.cmake")
  include("/home/runner/work/sageFlow/sageFlow/_codeql_build_dir/test/test_pipeline_basic[1]_tests.cmake")
else()
  add_test(test_pipeline_basic_NOT_BUILT test_pipeline_basic_NOT_BUILT)
endif()
