if(EXISTS "/home/runner/work/sageFlow/sageFlow/_codeql_build_dir/test/test_join_performance_methods[1]_tests.cmake")
  include("/home/runner/work/sageFlow/sageFlow/_codeql_build_dir/test/test_join_performance_methods[1]_tests.cmake")
else()
  add_test(test_join_performance_methods_NOT_BUILT test_join_performance_methods_NOT_BUILT)
endif()
