if(EXISTS "/home/runner/work/sageFlow/sageFlow/_codeql_build_dir/test/test_file_stream_source[1]_tests.cmake")
  include("/home/runner/work/sageFlow/sageFlow/_codeql_build_dir/test/test_file_stream_source[1]_tests.cmake")
else()
  add_test(test_file_stream_source_NOT_BUILT test_file_stream_source_NOT_BUILT)
endif()
